name: stocksense-prod
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      # Core web framework
      - fastapi==0.116.1
      - uvicorn==0.35.0
      - starlette==0.47.3

      # Data processing (memory optimized versions)
      - numpy<2.0.0 # More memory efficient than 2.x
      - pandas<2.0.0 # More memory efficient than 2.x

      # AI and ML (essential only)
      - langchain==0.3.27
      - langchain-core==0.3.75
      - langchain-google-genai==2.1.10
      - langgraph==0.6.6
      - google-ai-generativelanguage==0.6.18

      # Frontend
      - streamlit==1.49.0
      - plotly==6.3.0
      - altair==5.5.0

      # Database
      - peewee==3.18.2
      - sqlalchemy==2.0.43

      # Financial data
      - yfinance==0.2.65
      - newsapi-python==0.2.7

      # Essential utilities
      - requests==2.32.5
      - python-dotenv==1.1.1
      - pydantic==2.11.7

      # Remove heavy packages for production:
      # - torch (not needed for inference if using API)
      # - transformers (not needed if using Gemini API)
      # - huggingface-hub (not needed for production)
