name: stocksense-frontend
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.18
  - pip=25.2
  - pip:
      # Streamlit Frontend
      - streamlit==1.49.0
      - altair==5.5.0 # Streamlit charts
      - blinker==1.9.0 # Streamlit events
      - watchdog==6.0.0 # Streamlit file watching
      - tornado==6.5.2 # Streamlit server

      # Data Visualization
      - plotly==6.3.0
      - pandas<2.0.0 # Needed for data display
      - numpy<2.0.0 # Needed for plotly
      - pydeck==0.9.1 # Streamlit maps

      # Finance Data (Frontend charts)
      - yfinance==0.2.65

      # HTTP Client (API calls to backend)
      - requests==2.32.5
      - httpx==0.28.1

      # UI Utilities
      - pillow==11.3.0 # Image processing
      - pyarrow==21.0.0 # Data format support

      # Essential dependencies
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - click==8.2.1
      - idna==3.10
      - jinja2==3.1.6
      - markupsafe==3.0.2
      - packaging==25.0
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - six==1.17.0
      - urllib3==2.5.0
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - tqdm==4.67.1 # Progress bars
