name: stocksense-backend
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.18
  - pip=25.2
  - pip:
      # Core FastAPI Backend
      - fastapi==0.116.1
      - uvicorn==0.35.0
      - starlette==0.47.3
      # AI & LangChain (Core backend functionality)
      - langchain==0.3.27
      - langchain-core==0.3.75
      - langchain-google-genai==2.1.10
      - langchain-text-splitters==0.3.10
      - langgraph==0.6.6
      - langgraph-checkpoint==2.1.1
      - langgraph-prebuilt==0.6.4
      - langgraph-sdk==0.2.4
      - langsmith==0.4.20

      # Google AI
      - google-ai-generativelanguage==0.6.18
      - google-api-core==2.25.1
      - google-auth==2.40.3
      - googleapis-common-protos==1.70.0

      # Data Processing (Backend analytics)
      - numpy<2.0.0 # Pin for memory efficiency
      - pandas<2.0.0 # Pin for memory efficiency
      - yfinance==0.2.65
      - newsapi-python==0.2.7

      # Database
      - peewee==3.18.2
      - sqlalchemy==2.0.43

      # HTTP & Networking
      - httpx==0.28.1
      - httpcore==1.0.9
      - requests==2.32.5
      - requests-toolbelt==1.0.0

      # Utilities
      - python-dotenv==1.1.1
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - tenacity==9.1.2
      # Testing (Backend)
      - pytest==8.4.1

      # Essential dependencies
      - anyio==4.10.0
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - click==8.2.1
      - idna==3.10
      - jinja2==3.1.6
      - markupsafe==3.0.2
      - packaging==25.0
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - six==1.17.0
      - urllib3==2.5.0
      - typing-extensions==4.15.0
