# Generated by Django 5.2.5 on 2025-10-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlists', '0002_alter_watchlist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='name',
            field=models.CharField(default='My Watchlist', editable=False, max_length=100),
        ),
    ]
