# Generated by Django 5.2.5 on 2025-10-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
