# Streamlit Cloud secrets configuration
# Add your actual Render backend URL after deployment

[secrets]
BACKEND_URL = "https://your-app-name.onrender.com"

# Note: Replace "your-app-name" with your actual Render service name
# Example: https://stocksense-backend.onrender.com
